### ISSUE TITLE
Error in running the code.

### ISSUE THREAD

**Issue by sumo8291** [vector-1127/DAC#10]
Hi I have tried running your mnist.py code and I cam across several discrepancies. 

- I had to use dim_ordering='th' in the first Convolution2D().

- I have the following error after making the above change. I have added the screen-shot of the error. The line which causes this error is 123 of "mnist.py".
![error_init](https://user-images.githubusercontent.com/8149573/43705734-bf965098-99a6-11e8-8ee9-363c4a5dbf14.png)

Please can you help me address these issues.

Thanks

**Comment by vector-1127** [comment]
Which version of the theano are you using? The setting 'gpu3' sholud be changed when you use the code.

We use Keras 1.1.2 + Theano 0.8.2.
