### ISSUE TITLE
Error in layer Adaptive

### ISSUE THREAD

**Issue by tvmsouza** [vector-1127/DAC#12]
i get this error when i call cifar100.py:

-------------------------------------------------------------------------------------
Preallocating 3658/12194 Mb (0.300000) on cuda0
Mapped name None to device cuda0: TITAN Xp (0000:01:00.0)
Traceback (most recent call last):
  File "cifar100.py", line 150, in <module>
    z = Adaptive(norm = 2)(y)
  File "cifar100.py", line 63, in __init__
    super(Adaptive, self).__init__(**kwargs)
  File "/home/cleber/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 313, in __init__
    assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
AssertionError: Keyword argument not understood: norm
--------------------------------------------------------------------------------------
I think that the super class 'Layer' doenst have the parameter norm, find in call of layer Adaptive:
z = Adaptive(norm = 2)(y)

why you call the constructor of Adaptive w/ this parameter if it does not exist?

**Comment by vector-1127** [comment]
Hi,

Which version of the theano are you using?

We use Keras 1.1.2 + Theano 0.8.2.

**Comment by tvmsouza** [comment]
Hello vector.

Yes, i am using this versions.

However, using this version i got two errors, the problem with the adaptive layer and other with gpuarray/pygpu
-------------------------------------------------------------------------------------
Using Theano backend.
ERROR (theano.sandbox.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/cleber/anaconda3/envs/py36/lib/python3.6/site-packages/theano/sandbox/gpuarray/__init__.py", line 95, in <module>
    init_dev(config.device)
  File "/home/cleber/anaconda3/envs/py36/lib/python3.6/site-packages/theano/sandbox/gpuarray/__init__.py", line 46, in init_dev
    "Make sure Theano and libgpuarray/pygpu "
RuntimeError: ('Wrong major API version for gpuarray:', 2, 'Make sure Theano and libgpuarray/pygpu are in sync.')
Traceback (most recent call last):
  File "cifar100.py", line 150, in <module>
    z = Adaptive(norm = 2)(y)
  File "cifar100.py", line 63, in __init__
    super(Adaptive, self).__init__(**kwargs)
  File "/home/cleber/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 313, in __init__
    assert kwarg in allowed_kwargs, 'Keyword argument not understood: ' + kwarg
AssertionError: Keyword argument not understood: norm
----------------------------------------------------------------------------------------

So i installed new versions of keras and theano and run cifar100.py w/ the keras dataset cifar100 but the acquired result is almost 33~35% ACC and not 54%ACC like in the paper.

Do you know whats the problem?

Thanks.

**Comment by tvmsouza** [comment]
I did not find any keyword called norm for the layers of keras in any version of Keras. How do you intend to use it? "norm = 2"

**Comment by tvmsouza** [comment]
Only this kwargs are allowed in keras 1.1.2 from keras.engine.topology import Layer
-----------------------------------------------------------------------------------
 allowed_kwargs = {'input_shape',
                          'batch_input_shape',
                          'input_dtype',
                          'name',
                          'trainable'}

**Comment by vector-1127** [comment]
Hello,

I have modified this, just delete "norm=2".

In our paper, on CIFAR100, we achieve 23.75% ACC.

Thanks for your attention.

**Comment by tvmsouza** [comment]
Hi vector, but in your paper you achieve nmi: 0,3959 ari: 0,3059 acc: 0,5218 in the cifar10 dataset. But I can not reproduce this. I only achieve 33~34%. I ran cifar10 dataset on  cifar100.py script with the default configurations.

Uning the cifar10 dataset from keras:

from keras.datasets import cifar10

Its ok?

**Comment by vector-1127** [comment]
Hi,

Are you modify the number of neures in the last layers?

Can you report the results in CIFAR100?

The code of CIFAR10 will be reported in recent day, which has the same setting with the networks in CIFAR100.

The core code is the DAC* model that considers all the samples for training during each iteration.

Thanks for your attention.

Best regards.

**Comment by tvmsouza** [comment]
**"Can you report the results in CIFAR100?"**

I dont have the CIFAR20.h5 dataset. You can give to me?

**"Are you modify the number of neures in the last layers?"**

this is the places that i have change:

#data
**nb_classes = 10**
...
(X_train, y_true), (X_test, y_test) = cifar10.load_data()
X_train = np.vstack((X_train,X_test))
y_true = np.hstack((np.squeeze(y_true),np.squeeze(y_test)))
y_true = y_true.astype('int64')
...
x0 = Flatten()(x)
**x1 = Dense(nb_classes, init='identity')(x0)**
x1 = BatchNormalization(mode = 2)(x1)
x1 = Activation('relu')(x1)
x1 = Dense(nb_classes, init='identity')(x1)
x1 = BatchNormalization(mode = 2)(x1)
...
cluster_l1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.compile(optimizer='adam', 
              loss={'main_output':'binary_crossentropy','aux_output':'binary_crossentropy'}, 
              **loss_weights={'main_output':1,'aux_output':10})**

**Comment by vector-1127** [comment]
Hi,

You can find CIFAR100 at https://keras.io/datasets/.

We have reprocessed the data, i.e., subtract the mean.

Best regards.

**Comment by tvmsouza** [comment]
Thanks for the support.
I will try to reproduce the results again and I will notice you.

**Comment by vector-1127** [comment]
No problem.

Thanks for your attention.

Best regards.
