### ISSUE TITLE
CIFAR100 has 20 clusters

### ISSUE THREAD

**Issue by xu-ji** [vector-1127/DAC#13]
Hi, 
You use the 20 superclusters for CIFAR100, rather than the 100 finegrained ones. 

My question is, are the other baselines for 20 clusters or 100 clusters? In table 2 under "CIFAR100". http://openaccess.thecvf.com/content_ICCV_2017/papers/Chang_Deep_Adaptive_Image_ICCV_2017_paper.pdf 

Thanks.

**Comment by vector-1127** [comment]
Hello,

We use the 20 superclusters for CIFAR100, which is also used in the other baselines.
