### ISSUE TITLE
Request for the rest of the code

### ISSUE THREAD

**Issue by xu-ji** [vector-1127/DAC#7]
You use a loss, binary_crossentropy on `aux_output`, which was not discussed in the paper. And the accuracy reported in the log is different to the reported results in the paper. Please could you upload the code that actually generated the reported results, for ImageNet and STL10, and in particular clarify if you used the additional `aux_output` loss for these reported results.

**Comment by vector-1127** [comment]
Hello, the myMetrics package is updated at https://github.com/vector-1127/DAC.

We have further set more preferable hyper-parameter for better performances, including the network structures (https://github.com/vector-1127/DAC/issues/5). The other code will be released in recent.

**Comment by vector-1127** [comment]
Hi, 
The aux_output can be treated as a prior. That is, the original image and the rotated image have the same label features. It is just a trick for our model, which is similar to the denoising auto-encoder, etc..

**Comment by vector-1127** [comment]
Hi,
The aux_output can be treated as a prior. That is, the original image and the rotated image have the same label features. It is just a trick for our model, which is similar to the denoising auto-encoder, etc..

For the image data, this is work. For text or speech signals, additional experiments are needed in the future.
