### ISSUE TITLE
Clarification of dataset

### ISSUE THREAD

**Issue by xu-ji** [vector-1127/DAC#8]

**Comment by vector-1127** [comment]
Hello,

The chosen 10 classes have been released at https://github.com/vector-1127/DAC/blob/master/Datasets_description/ImageNet-10.txt.

The function has been upload at https://github.com/vector-1127/DAC/blob/master/Datasets_description/read_data.py.

More details can be founded at https://github.com/vector-1127/DAC/tree/master/Datasets_description.
