### ISSUE TITLE
Why do you test on the training set?

### ISSUE THREAD

**Issue by xu-ji** [vector-1127/DAC#9]
For ImageNet script. This will give misleading accuracy because the test data is not unseen.

**Comment by vector-1127** [comment]
Hi,
This setting is following the previous work, i.e., DEC (J. Xie, R. Girshick, and A. Farhadi. Unsupervised deep embedding for clustering analysis. In ICML, pages 478–487, 2016.) and JULE (J. Yang, D. Parikh, and D. Batra. Joint unsupervised learning of deep representations and image clusters. In CVPR, pages 5147–5156, 2016.).
